services:
  download:
    build: .
    container_name: download
    ports:
      - "8080:8080"               # 映射端口
    volumes:
      - ./downloads:/app/downloads   # 映射文件目录
      - /var/run/docker.sock:/var/run/docker.sock    # 这里不能更改
    restart: always
