services:
  download:
    build: .
    container_name: download
    ports:
      - "8080:8080"
    environment:
      - APP_PASSWORD=admin             # 登录密码
    volumes:
      - ./downloads:/root/downloads    # 映射文件目录
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always